### ISSUE TITLE
Vérification figure ssection 9.12.4

### ISSUE THREAD

**Issue by adethise** [petervanroy/lingi1101#14]
(section 9.12.4, partie 22) La figure indique que ++- est une instabilité faible, --- est une instabilité forte. Est-ce correct ?

**Comment by petervanroy** [comment]
On 15/01/15 12:33, adethise wrote:
>
> (section 9.12.4, partie 22) La figure indique que ++- est une 
> instabilité faible, --- est une instabilité forte. Est-ce correct ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/petervanroy/lingi1101/issues/14>.
>
Oui, c'est correct.  Un graphe complet qui est faiblement équilibré peut 
avoir une instabilité forte (---) en plus des deux cas stables (+++ et 
+--).  On peut accepter le --- mais pas le ++-.  Le ++- n'est pas 
durable: les deux ennemis ont une forte tendance à devenir des amis.

Peter
