### ISSUE TITLE
Solution au problème de PageRank

### ISSUE THREAD

**Issue by adethise** [petervanroy/lingi1101#16]
(section 11.2, partie 24) La sous-section indique "solution au problème : fermer la boucle, créer des cycles". Quelle boucle, quels cycles ?

**Comment by petervanroy** [comment]
On 15/01/15 13:02, adethise wrote:
>
> (section 11.2, partie 24) La sous-section indique "solution au 
> problème : fermer la boucle, créer des cycles". Quelle boucle, quels 
> cycles ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/petervanroy/lingi1101/issues/16>.
>
Dans la première version naïve de PageRank, l'eau ne peut jamais sortir 
d'un noeud qui ne contient que des liens entrants.  L'eau ne *circule* 
donc pas, elle s'accumule dans ces noeuds.  Pour *fermer la boucle* il 
faut que l'eau puisse sortir d'un noeud même s'il n'y a pas de liens 
entrants.  La solution est de simuler l'évaporation + la précipitation: 
on enlève une proportion de l'eau égale à 1-S et on met cette partie 
partout de façon égale.  Cela *ferme* la boucle parce que l'eau peut 
circuler.  Cela correspond mieux à la façon dont les gens utilisent le 
Web (illustrée par la marche aléatoire): ils se mette quelque part et 
ils "surfent" quelques pas, ensuite ils répètent la même chose.

Peter

**Comment by adethise** [comment]
Ajouté et clarifié dans le syllabus.
