### ISSUE TITLE
Logique des propositions - Table de vérité

### ISSUE THREAD

**Issue by fthuin** [petervanroy/lingi1101#18]
Pour bien faire, il faudrait qu'on utilise que des lettres majuscules dans les tables de vérités car les explications utilisent cette notation, du coup les explications n'ont pas de sens direct avec les tableaux qui y sont liés.

**Comment by VanStratum** [comment]
Les majuscules désignent un identificateur alors que les minuscule
désignent n'importe quelle proposition.
